### ISSUE TITLE
Não permite alteração de cadastro de usuário.

### ISSUE THREAD

**Issue by iamjpeil** [angelogluz/LocadoraSpringBoot#25]
A página de cadastro de usuário não da a possibilidade de alteração de usuário, que faz com que  integridade dos dados seja afetada.

**Comment by dionatanmelo** [comment]
Não é possível deletar usuário pelo seu id, ao solicitar a requisição DELETE, retorna a pagina 404.

**Comment by dionatanmelo** [comment]
Ao solicitar a requisição DELETE, para todos os usuários, então é retornado a página 204, que é quando o servidor encerra o processo, pois não recebe os dados do processo de requisição.
