### ISSUE TITLE
Não permite exclusão de usuário.

### ISSUE THREAD

**Issue by iamjpeil** [angelogluz/LocadoraSpringBoot#26]
A página de cadastro de usuário não da a possibilidade de exclusão de usuário, que faz com que cadastros que não eram pra acontecer permaneçam ao olhar do utilizador sem possibilidade de ação do mesmo.

**Comment by dionatanmelo** [comment]
Não é possível deletar usuário pelo seu id, ao solicitar a requisição DELETE, retorna a pagina 404.

**Comment by dionatanmelo** [comment]
Ao solicitar a requisição DELETE, para todos os usuários, então é retornado a página 204, que é quando o servidor faz o processo com sucesso mas logo encerra, pois não recebe os dados do processo de requisição.
