### ISSUE TITLE
Não permite alterar nem excluir filmes

### ISSUE THREAD

**Issue by andremaia1** [angelogluz/LocadoraSpringBoot#32]
O sistema não apresenta as opções de alteração de dados e/ou de exclusão de um filme.

**Comment by dionatanmelo** [comment]
Como mencionado acima, visualmente não é possível deletar um filme, mas solicitando a requisição pela rota da API é possível, porém é apresentado a exceção 204, assim como foi apresentado na exclusão de usuários.

**Comment by dionatanmelo** [comment]
![captura de tela20171018093728](https://user-images.githubusercontent.com/26264022/31734759-49ae10b2-b42f-11e7-904a-fe32dbf481c5.png)
