### ISSUE TITLE
Campos de datas mal formatados

### ISSUE THREAD

**Issue by alanarcorrea** [angelogluz/LocadoraSpringBoot#6]
Campos "Data de Locação" e "Data de Entrega" do menu "Locação" não estão formatados corretamente para visualizar datas no formato PT-BR.

**Comment by cineasthales** [comment]
O último sempre é adicionado em um formato completo (dia da semana, mês, dia, hora, fuso horário e ano) e os demais ficam no formato data AAAA-MM-DD.
Deveria ser tudo DD/MM/AAAA.
